# Generated by Django 3.2.6 on 2021-08-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('body', models.CharField(max_length=320)),
                ('labels', models.CharField(max_length=155)),
                ('image', models.URLField()),
                ('status', models.BooleanField()),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_api.list')),
            ],
        ),
    ]
