# Generated by Django 3.2.6 on 2021-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='labels',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
